### ISSUE TITLE
Calendar View - Iterations & Days off (links) - on-premise TFS

### ISSUE THREAD

**Issue by GABecker** [Microsoft/vsts-team-calendar#160]
Having issues with clicking the links for Iterations or Days off from the calendar view.  In our on premise version of TFS 2017 update 2 when we use the links it will open a new tabbed window for Iteration or Capacity of the current sprint..  If try to create a new iteration we get this error "TF400813: Resource not available for anonymous access. Client authentication required.".  If we go to Days off we get an error when the page loads "TF400813: Resource not available for anonymous access. Client authentication required. Session Id: 9f579401-0176-41b3-9c25-c0792743ac93".  Any action taken in the new window assumes a anonymous identity.  We have to close those tabs and add everything with out using these shortcuts from the calendar.  I have tried I.E., Edge, and Chrome all behave the same way.  Any thoughts on how to address this issue?

**Comment by dmarcey** [comment]
Thanks for reporting. The issue has been fixed. Within 24 hours, you should see the fix in your on-premises deployment.

**Comment by GABecker** [comment]
I have tested this.. It works with Iterations now however, when clicking Days off I am still getting the following error.

TF400813: Resource not available for anonymous access. Client authentication required.
Session Id: d15cd60f-43fe-458e-a6df-e60572702f22
